apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.config.hostname }}`)
    services:
    - kind: Service
      name: {{ include "common.names.fullname" . }}
      namespace: {{ .Release.Namespace | quote }}
      port: http
  tls:
    secretName: {{ .Values.config.hostname | quote }}
    domains:
    - main: {{ .Values.config.hostname | quote }}